- name: Create Gunicorn dir
  file:
    name: '{{ gunicorn_dir }}'
    state: directory

- name: Create Gunicorn config
  template:
    src: templates/conf.py
    dest: '{{ gunicorn_dir }}/{{ app_name }}.py'
    owner: root
    group: root
    mode: 0644